version: '3.7'
services:
  node:
    container_name: emiss-api
    image: emiss-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - DB_USER=postgres
      - DB_HOST=host.docker.internal
      - DB_NAME=russtat
      - DB_PASSWORD=postgres
      - DB_PORT=5432
